FROM almalinux:9
RUN dnf install nginx -y
CMD ["nginx","-g","daemon off;"]
LABEL author="phani"

# Here MAINTAINER is depricated . It is like author for this image . we can add it like label with key author