FROM almalinux:9
# RUN cd/tmp
# RUN pwd       #it wont show current working directory

RUN mkdir /app
WORKDIR /app
RUN pwd     
# Now it will display cuttent working directory
CMD ["sleep","1000"]