FROM almalinux:9
# CMD ["ping","google.com"]

# If we run    docker run entry:v1 ping facebook.com . It will ping to facebook.com means it is overriding CMD
# where as ENTRYPOINT cannot overrided

# ENTRYPOINT ["ping","google.com"]

CMD ["google.com"]

ENTRYPOINT ["ping"]
